<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

  <xacro:property name="baseLength" value="0.8255" />
  <xacro:property name="baseWidth" value="0.6985" />
  <xacro:property name="baseHeight" value="0.1" />

  <xacro:property name="baseMass" value="27" />
  <xacro:property name="wheelMass" value="0.453592" />

  <xacro:property name="wheelWidth" value="0.0254" />
  <xacro:property name="wheelRadius" value="0.0762" />

  <xacro:property name="wheelOffset" value="0.25" />

  <xacro:property name="camMass" value="0.05" />
  <xacro:property name="camWidth" value="0.1016" />
  <xacro:property name="camRadius" value="0.0127" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find robot_urdf)/urdf/robot.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find robot_urdf)/urdf/materials.xacro" />

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${baseLength} ${baseWidth} ${baseHeight}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${baseLength} ${baseWidth} ${baseHeight}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${baseMass}"/>
      <inertia ixx="${(1/12) * baseMass * ((baseHeight * baseHeight) + (baseLength * baseLength))}" ixy="0.0" ixz="0.0" iyy="${(1/12) * baseMass * ((baseWidth * baseWidth) + (baseLength * baseLength))}" iyz="0.0" izz="${(1/12) * baseMass * ((baseWidth * baseWidth) + (baseHeight * baseHeight))}"/>
    </inertial>
  </link>

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="0 1.57075 1.57075" xyz="0 ${-wheelWidth/2} 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="0 1.57075 1.57075" xyz="0 ${-wheelWidth/2} 0"/>
    </collision>
    <inertial>
      <mass value="${wheelMass}"/>
      <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
    </inertial>
  </link>

  <joint name="base_to_front_right_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="${wheelOffset} ${-baseWidth /2} 0"/>
  </joint>

  <link name="back_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="0 1.57075 1.57075" xyz="0 ${-wheelWidth/2} 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="0 1.57075 1.57075" xyz="0 ${-wheelWidth/2} 0"/>
    </collision>
    <inertial>
      <mass value="${wheelMass}"/>
      <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
    </inertial>
  </link>

  <joint name="base_to_back_right_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="back_right_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="${-wheelOffset} ${-baseWidth /2} 0"/>
  </joint>

  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="0 1.57075 1.57075" xyz="0 ${wheelWidth/2} 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="0 1.57075 1.57075" xyz="0 ${wheelWidth/2} 0"/>
    </collision>
    <inertial>
      <mass value="${wheelMass}"/>
      <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
    </inertial>
  </link>

  <joint name="base_to_front_left_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="${wheelOffset} ${baseWidth /2} 0"/>
  </joint>

  <link name="back_left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="0 1.57075 1.57075" xyz="0 ${wheelWidth/2} 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheelWidth}" radius="${wheelRadius}"/>
      </geometry>
      <origin rpy="0 1.57075 1.57075" xyz="0 ${-wheelWidth/2} 0"/>
    </collision>
    <inertial>
      <mass value="${wheelMass}"/>
      <inertia ixx="0.4" ixy="0.0" ixz="0.0" iyy="0.4" iyz="0.0" izz="0.2"/>
    </inertial>
  </link>

  <joint name="base_to_back_left_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="back_left_wheel"/>
    <axis xyz="0 1 0"/>
    <origin xyz="${-wheelOffset} ${baseWidth /2} 0"/>
  </joint>

  <!-- Sensors -->

  <!-- Hokuyo Laser -->

  <joint name="laser_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0.41275 0 0.35" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="laser"/>
  </joint>

  <link name="laser">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://robot_urdf/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <!-- Kinect

  <joint name="d435_joint" type="fixed">
    <axis xyz="0 0 0" />
    <origin xyz="0.41275 0 0.225" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="d435_link"/>
  </joint>
  
  <link name="d435_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	      <box size="0.02 0.07 0.02"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.02 0.07 0.02"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  -->
</robot>